### ISSUE TITLE
Smart Contract 이용하여 금액 및 주소 조회

### ISSUE THREAD

**Issue by beetles86** [codestates/BTAdAppProject-10#7]
### ISSUE
- Detail: Smart Contract 이용하여 금액 및 주소 조회

### TODO
1. [ ] Smart Contract 금액 조회
2. [ ] Smart Contract 주소 조회
3. [ ] 조회 값 화면에 반영

### Estimated time
> Pick one
`0.5d`
